PoC Heap and random number generator implementations
ricky26/rust-mega-drive pull request #7
Opened 2021-06-30 11:09 UTC by reinvantveer

Draft: this isn't compiling yet because of mutability issues in the allocator

2021-07-01 19:05 UTC, ricky26 requested changes
I think you still said this is a WIP but I've had a look through it anyway.

Thank you very much for your effort!

2021-07-01 19:05 UTC, ricky26 commented on examples/megacoinflip/entry.S
> +.text
:cry: I wish I'd found time to get rid of this last little bit of assembly... it should be possible. For now I guess it's fine to copy it.

2021-07-01 19:05 UTC, ricky26 commented on examples/megacoinflip/src/lib.rs
> +    unsafe { ALLOCATOR.init(HEAP_BOTTOM, HEAP_SIZE) }
It's probably best not to pass in what is effectively a pointer as an integer here, can we make this use the `heap` method?

2021-07-01 19:05 UTC, ricky26 commented on libs/megadrive-sys/src/heap.rs
> +// This is basically a lightly refactored version of Philipp Oppermann's
This should probably not live in the `-sys` crate.

The `-sys` crate is really only designed to have the platform bindings in (in this case, they're more like drivers).

I think we'd be better off with this in a separate crate that relies on `-sys`. Perhaps have our own `megadrive-alloc`?

2021-07-01 19:05 UTC, ricky26 commented on libs/megadrive-sys/src/heap.rs
> +    pub unsafe fn new(heap_bottom: usize, heap_size: usize) -> Heap {
If we're making this megadrive-specific we can probably add another constructor method which automatically calls our magical `heap()` function to get the size of the available heap.

2021-07-01 19:05 UTC, ricky26 commented on libs/megadrive-sys/src/heap.rs
> +const HEAP: Mutex<Heap> = Mutex::default();
Ah, this is where the mutexes are turning up! Since we can't actually multithread (making Mutexes which block rather pointless), you can probably use `RefCell<>` or `Rc<RefCell<>>` here instead! (They both live in `core` thankfully.)

2021-07-01 19:05 UTC, ricky26 commented on libs/megadrive-sys/src/hole.rs
> +// https://raw.githubusercontent.com/phil-opp/linked-list-allocator/v0.5.0/src/hole.rs
It looks like these are OK license-wise to use.

2021-07-01 19:05 UTC, ricky26 commented on libs/megadrive-sys/src/rng.rs
> +use core::ptr::read_volatile;
This could probably also do with not living in `-sys`. Maybe we do just need a more generic library crate for megadrive with useful (but not driver-level) code.

2021-07-01 19:26 UTC, reinvantveer commented on examples/megacoinflip/entry.S
> +.text
Ahh that's totally fine. Just a bit of boilerplate, no bigs.

2021-07-01 19:27 UTC, reinvantveer commented on libs/megadrive-sys/src/heap.rs
> +// This is basically a lightly refactored version of Philipp Oppermann's
Ah yes I was hesitent to put it there, but a separate crate sounds good

2021-07-01 19:31 UTC, reinvantveer commented on libs/megadrive-sys/src/rng.rs
> +use core::ptr::read_volatile;
Agreed

2021-07-01 19:32 UTC, reinvantveer commented on examples/megacoinflip/src/lib.rs
> +    unsafe { ALLOCATOR.init(HEAP_BOTTOM, HEAP_SIZE) }
Thanks I'll check it out

2021-07-02 19:54 UTC, reinvantveer commented on libs/megadrive-sys/src/heap.rs
> +// This is basically a lightly refactored version of Philipp Oppermann's
Resolved in https://github.com/ricky26/rust-mega-drive/pull/7/commits/5c008b7ff283ec48cccb1e7e091c0663368019c9

2021-07-03 15:41 UTC, reinvantveer commented on libs/megadrive-sys/src/rng.rs
> +use core::ptr::read_volatile;
Fixed in https://github.com/ricky26/rust-mega-drive/pull/7/commits/e371dd36780de4061c19bfbf19577aa6f1122799

2021-07-05 17:03 UTC, reinvantveer commented on libs/megadrive-sys/src/heap.rs
> +const HEAP: Mutex<Heap> = Mutex::default();
Fixed in https://github.com/ricky26/rust-mega-drive/pull/7/commits/c736cbc74686056dea43686a3de3b8cd7e322447. This totally makes me look like I write allocators for breakfast any day. They dont't call me Allocator-Dundee for nothing! :crocodile:

2021-07-05 17:04 UTC, reinvantveer commented on libs/megadrive-sys/src/heap.rs
> +const HEAP: Mutex<Heap> = Mutex::default();
I settled for a simple `RefCell` since I can't see a use for `Rc<RefCell>` yet but please enlighten me if you do.

2021-07-05 17:06 UTC, reinvantveer commented on libs/megadrive-sys/src/heap.rs
> +    pub unsafe fn new(heap_bottom: usize, heap_size: usize) -> Heap {
Dropped it in https://github.com/ricky26/rust-mega-drive/pull/7/commits/ea1c5098706def417879e59eb04754c432cda35a as it appears unused. `empty()` followed by `init()` should be enough.

2021-07-05 17:10 UTC, reinvantveer commented on examples/megacoinflip/src/lib.rs
> +    unsafe { ALLOCATOR.init(HEAP_BOTTOM, HEAP_SIZE) }
Fixed in https://github.com/ricky26/rust-mega-drive/pull/7/commits/7a6f976159ab336bc2015469a4b34e07fdc36b64 but I'm unsure this works this way

2021-07-06 19:30 UTC, reinvantveer commented
For some very interesting effects: do
```
        flipped.push(coin); // mask with 1, so either 0 or 1

        let heads_or_tails_tile_idx = match flipped.pop() {
            None => {coin + 1}
            Some(pushed) => {pushed + 1}
        };
```

2021-07-06 21:25 UTC, ricky26 requested changes

2021-07-06 21:25 UTC, ricky26 commented on libs/megadrive-alloc/src/lib.rs
> +#![feature(allocator_api)]
I don't think you need this to override just the global allocator.

2021-07-06 21:25 UTC, ricky26 commented on libs/megadrive-alloc/src/lib.rs
> +#![feature(const_mut_refs)]
I think if you use `static`s instead of `const`s where you need mutability, this won't be needed.

2021-07-06 21:25 UTC, ricky26 commented on libs/megadrive-util/src/rng.rs
> +            let hv_counter = read_volatile(&GFX_HVCOUNTER_PORT) as u16;
Actually, your comment has made me realise that this code isn't quite right.

`read_volatile` reads a reference with an atomic read. Using `read_volatile(&MY_CONST)` will just return you the value of `MY_CONST`. 

I think you really need to do something like `const GFX_HVCOUNTER_PORT: *const u16 : 0xc00008 as _;`, then just `read_volatile(GFX_HVCOUNTER_PORT)`.

It can never be a null pointer dereference because the address is not 0. :smile:

2021-07-06 21:27 UTC, ricky26 commented
> ```
> # In Register Scavenger
> # Machine code for function main: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten
> Frame Objects:
>   fi#0: size=12, align=4, at location [SP-52]
> ... [lots of dumping]
> - operand 1:   implicit killed $ccr
> LLVM ERROR: Found 1 machine code errors.
> error: could not compile `megacoinflip`
> ...
> ```

Oh, that's not good news. I did make some changes into how the CCR was used as a quick hack around the current codegen (it was 'forgetting' conditionals). I'm not sure when I'll find time to look into this. :cry:

2021-07-07 13:21 UTC, reinvantveer commented on libs/megadrive-alloc/src/lib.rs
> +#![feature(allocator_api)]
Checked, but I'm being told by the compiler that it is:
```
error[E0658]: use of unstable library feature 'allocator_api'
 --> libs/megadrive-alloc/src/heap.rs:7:27
  |
7 | use core::alloc::{Layout, AllocError, GlobalAlloc};
  |                           ^^^^^^^^^^
  |
  = note: see issue #32838 <https://github.com/rust-lang/rust/issues/32838> for more information
  = help: add `#![feature(allocator_api)]` to the crate attributes to enable
```

2021-07-07 13:34 UTC, reinvantveer commented on libs/megadrive-alloc/src/lib.rs
> +#![feature(const_mut_refs)]
The trouble is that the `const` being returned is in a `const fn` 
```
impl HoleList {
    pub const fn empty() -> HoleList {
        HoleList { ... }
```
that is rather tricky to refactor. It doesn't want to return a statically defined `HoleList`. So this would imply re-writing Phiipp's heap implementation I fear.

2021-07-07 13:36 UTC, reinvantveer commented on libs/megadrive-util/src/rng.rs
> +            let hv_counter = read_volatile(&GFX_HVCOUNTER_PORT) as u16;
Hahaha it worked great, just having an address as a starting seed! It definitely _was_ pseudo-random :rofl:

2021-07-07 13:52 UTC, reinvantveer commented on libs/megadrive-util/src/rng.rs
> +            let hv_counter = read_volatile(&GFX_HVCOUNTER_PORT) as u16;
Fixed in https://github.com/ricky26/rust-mega-drive/pull/7/commits/b44f9ac4a0367a8490d2182f609878242c5fdc21

2021-07-07 19:50 UTC, reinvantveer commented
> Oh, that's not good news. I did make some changes into how the CCR was used as a quick hack around the current codegen (it was 'forgetting' conditionals). I'm not sure when I'll find time to look into this.

I understand. So this would be the "condition code register" and it's been disabled in the LLVM version we use? Is that correct?

2021-07-09 15:02 UTC, reinvantveer commented
> > Oh, that's not good news. I did make some changes into how the CCR was used as a quick hack around the current codegen (it was 'forgetting' conditionals). I'm not sure when I'll find time to look into this.
> 
> I understand. So this would be the "condition code register" and it's been disabled in the LLVM version we use? Is that correct?
> Perhaps you can point me to the associated commits you made? I can't make promises on understanding any of it, but I'm just curious.
> 
> Ah I see it's in [ricky26/llvm-project@d7a0d7c](https://github.com/ricky26/llvm-project/commit/d7a0d7c094b779985e01bdf34474e9dd7469556b)

I think we can let this go for now, we can work around this. I've opened a new issue in #8

2021-07-09 15:58 UTC, reinvantveer commented on libs/megadrive-alloc/src/heap.rs
> +        self.holes = HoleList::new(self.bottom, self.size);
@ricky26 did I get this right?

2021-07-14 08:46 UTC, ricky26 commented on libs/megadrive-alloc/src/heap.rs
> +        self.holes = HoleList::new(self.bottom, self.size);
I expected you to factor out the existing init method and call out to it, but this is fine. It looks correct. :smile:

2021-07-14 08:53 UTC, ricky26 commented on libs/megadrive-alloc/src/lib.rs
> +#![feature(allocator_api)]
You don't need to reference AllocError any more though - that was just related to the allocator API (which is separate from the global allocator). As far as I can see, it's returned from one function as an error, that function is only called with `.ok()` on it, so it's only ever discarded.

2021-07-14 08:57 UTC, ricky26 commented on libs/megadrive-alloc/src/lib.rs
> +#![feature(const_mut_refs)]
You can populate statics from const fns too.

2021-07-14 08:58 UTC, ricky26 commented
> > Oh, that's not good news. I did make some changes into how the CCR was used as a quick hack around the current codegen (it was 'forgetting' conditionals). I'm not sure when I'll find time to look into this.
> 
> I understand. So this would be the "condition code register" and it's been disabled in the LLVM version we use? Is that correct?
> Perhaps you can point me to the associated commits you made? I can't make promises on understanding any of it, but I'm just curious.
> 
> Ah I see it's in [ricky26/llvm-project@d7a0d7c](https://github.com/ricky26/llvm-project/commit/d7a0d7c094b779985e01bdf34474e9dd7469556b)

It's not that the register has been disabled. The 'implicit killed' means that the register has been clobbered at that instruction (overwritten, effectively). It's a compiler bug - it shouldn't've been overwritten.

2021-07-14 09:05 UTC, ricky26 requested changes
Sorry for taking so long to look at this again.

I want to make some time to try and figure out what's going on with the invalid codegen but I'm not sure I'll be able to find the time soon. I'd also really like to figure out what the core issue with CCR codegen is and try and get that upstreamed instead.

2021-07-14 09:05 UTC, ricky26 commented on libs/megadrive-alloc/src/heap.rs
> +const HEAP: RefCell<Heap> = RefCell::new(Heap::empty());
```suggestion
static HEAP: RefCell<Heap> = RefCell::new(Heap::empty());
```

We expect this to be mutated, so it shouldn't be const.

2021-07-14 16:00 UTC, reinvantveer commented on libs/megadrive-alloc/src/lib.rs
> +#![feature(allocator_api)]
I managed to figure this one out succesfully :raised_hands:, fixed in https://github.com/ricky26/rust-mega-drive/pull/7/commits/1bbf1b8c2d659997e42912efc718126d832980df

2021-07-14 16:02 UTC, reinvantveer commented on libs/megadrive-alloc/src/heap.rs
> +        self.holes = HoleList::new(self.bottom, self.size);
Cool

2021-07-14 16:11 UTC, reinvantveer commented
> Sorry for taking so long to look at this again.
> 
> I want to make some time to try and figure out what's going on with the invalid codegen but I'm not sure I'll be able to find the time soon. I'd also really like to figure out what the core issue with CCR codegen is and try and get that upstreamed instead.

Thanks ever so much for "mentoring" me through this. 
The megacoinflip still isn't flipping though, unfortunately. I'm kinda missing the debugging tools to figure this one out, there's no convenient stack trace or panic info to see what's missing or going wrong... This one needs a very close read, or some more debug tools like a RetroArch/BlastEm gdb session or something, or maybe even a panic handler that shows some debug info on screen.

2021-07-14 19:53 UTC, ricky26 commented
I've been using BlastEm's built-in gdb prompt for a lot of the testing I've done. Generally I've had to view a disassembly of my outputs along-side though since the built-in prompt doesn't read debug information - so not for the feint of heart!

2021-07-15 07:55 UTC, reinvantveer commented
> I've been using BlastEm's built-in gdb prompt for a lot of the testing I've done. Generally I've had to view a disassembly of my outputs along-side though since the built-in prompt doesn't read debug information - so not for the feint of heart!

Hmmm I'm going to see whether I can cook up something slightly less involved than that, having looked at a GDB debug session only once before. Also this reminds me: some people do amazing things with hardware debuggin hardware - you may possible have seen https://hackaday.io/project/1507-usb-megadrive-devkit as an open hardware using the GDB remote serial debug interface, which totally blew my mind.

2021-07-18 18:57 UTC, reinvantveer commented on libs/megadrive-alloc/src/lib.rs
> +#![feature(const_mut_refs)]
This one is a little beyond me, I'm afraid:
```
error[E0658]: mutable references are not allowed in constant functions
  --> libs/megadrive-alloc/src/hole.rs:20:23
   |
20 |                 next: None,
   |                       ^^^^
   |
   = note: see issue #57349 <https://github.com/rust-lang/rust/issues/57349> for more information
   = help: add `#![feature(const_mut_refs)]` to the crate attributes to enable
```
I suspect this has to do with
```
pub struct Hole {
    size: usize,
    next: Option<&'static mut Hole>,
}
```
But I'm stumped beyond this. Can you perhaps point me in the direction of a possible solution on this?

2021-08-12 11:56 UTC, parasyte commented on libs/megadrive-alloc/src/heap.rs
> +            .borrow_mut()
This can potentially introduce Undefined Behavior.

* `RefCell::borrow_mut()` will panic at runtime if it is already borrowed: https://doc.rust-lang.org/core/cell/struct.RefCell.html#method.borrow_mut
* `GlobalAlloc` is not allowed to panic: https://doc.rust-lang.org/core/alloc/trait.GlobalAlloc.html#safety

The panic can occur with re-entrant allocations or unfortunately timed interrupt handlers which need to allocate. These cases are unlikely, but it is better to use `UnsafeCell` directly and add a critical section to protect against interrupts.

It is not enough to just say "re-entrant allocations and interrupt handlers that allocate are Undefined Behavior" because you know someone is going to do it anyway, and more importantly these things do not have to be Undefined Behavior.

2021-08-12 12:17 UTC, parasyte commented on libs/megadrive-alloc/src/lib.rs
> +#![feature(const_mut_refs)]
You can workaround this by lazily initializing the static allocator instead of using const functions.

This is easy with `UnsafeCell<Option<T>>`: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=15c46e35b8e65885057048ce53e47e10 This example just assumes that `Alloc::init()` will not be interrupted.

2021-08-18 17:33 UTC, reinvantveer commented on libs/megadrive-alloc/src/heap.rs
> +            .borrow_mut()
I managed to write a compiling allocator based on unsafe cell interior mutability, but unfortunately this now runs into #4. I stored this in a separate branch of my fork, in https://github.com/reinvantveer/rust-mega-drive/tree/unsafe_cell_linked_list_allocator but I'm not too confident that the 32-bit multiplication issue can be resolved.

I'm going to try if this happens with a simple bump allocator as you showed in the playground example, and hope that this will result in at least a minimalistic heap implementation. Otherwise, we'll just have to go heapless :grin:

2021-10-10 12:08 UTC, reinvantveer commented
I'm going to close this one, I'll look into a heap allocator at some point in time again, but I made the mistake of pushing all of my commits to my default branch instead of a feature branch. I'm going to save my work in a branch and pull my main branch even with the main branch here again to clean things up.

Maybe there's a way to implement some kind of interior mutable type without the 32-bit mutliplication problem popping up, but at the moment I'm not seeing it unfortunately.

2021-10-10 12:08 UTC, closed without merging