Text rendering using a "default" font
ricky26/rust-mega-drive pull request #9
Opened 2021-07-24 14:38 UTC by reinvantveer

2021-07-25 10:47 UTC, reinvantveer commented
Looks that I can try to [override the core panic macro](https://stackoverflow.com/questions/45864495/can-i-override-a-macro-from-the-standard-library-with-my-own-custom-macro#45865101)

2021-08-15 20:37 UTC, reinvantveer commented
@ricky26 do you have the time do a review of this? Do you have objections on pulling in Python code to generate the Rust file containing the font data?

2021-08-23 18:45 UTC, ricky26 requested changes
Hi there! I'm sorry it's taken me _so long_ to get around to this.

It's a jaded excuse but work has been busy. :sweat_smile:

Personally, I do have a pretty strong preference for using a `build.rs`-based script for font generation. The practical benefit being that it's much easier to get cargo to run those kind of things as part of the build, which in turn makes including them in libraries far less convoluted.

I don't have any major objections to anything else (just one minor niggle). It might be worth however considering @parasyte's [comment from the discussion about the RNG](https://github.com/ricky26/rust-mega-drive/discussions/3#discussioncomment-1163058) if you're including the RNG in this PR, though that library might fall foul of the same missing intrinsics as you ran into before.

(Again, sorry it's taken me so long to get through this.)

2021-08-23 18:45 UTC, ricky26 commented on ascii_rs_generator/pillow_default_font.py
> +import math
It would be nice to be able to run these inside the cargo ecosystem as part of a `build.rs` script. There's some pretty good prior art for this.

2021-08-23 18:45 UTC, ricky26 commented on ascii_rs_generator/pillow_default_font.py
> +    rust_file = open(output_path, 'at')
```suggestion
    with open(output_path, 'at') as rust_file:
```

2021-08-23 18:45 UTC, ricky26 commented on libs/megadrive-util/src/panic.rs
> +#[panic_handler]
:thinking: It might be worth having this function be available as a library but only map it as `#[panic_handler]` if a library feature is on. (That'll allow people to use the megadrive-util library and opt out of the default panic handler.)

2021-08-24 19:36 UTC, reinvantveer commented
> Hi there! I'm sorry it's taken me _so long_ to get around to this.
No worries. It took the Mega Drive 30 years to reach integration with Rust, it has few moments to spare :)

2021-08-24 19:39 UTC, reinvantveer commented on ascii_rs_generator/pillow_default_font.py
> +    rust_file = open(output_path, 'at')
Hahah that's a classic optimization! That I let that one slip! :laughing:

2021-08-31 18:14 UTC, reinvantveer commented on libs/megadrive-util/src/panic.rs
> +#[panic_handler]
Good idea. Resolved (I think) in https://github.com/ricky26/rust-mega-drive/pull/9/commits/82a2ad5e11da48c32077f40a29b1f1807f8a6d8f

2021-08-31 18:16 UTC, reinvantveer commented on ascii_rs_generator/pillow_default_font.py
> +import math
OK, let me see if I can get this straight. You mean something like:
`cargo megadrive generate-font default`? Which in turn runs the Python script in a subprocess, that generates the font rust file?

2021-08-31 18:18 UTC, reinvantveer commented on ascii_rs_generator/pillow_default_font.py
> +import math
Ah, I see I have some reading up to do on https://doc.rust-lang.org/cargo/reference/build-scripts.html

2021-09-04 17:45 UTC, reinvantveer commented on ascii_rs_generator/pillow_default_font.py
> +import math
Cool, I got this to run using buld.rs!

2021-09-04 17:48 UTC, reinvantveer commented on ascii_rs_generator/pillow_default_font.py
> +import math
Just let me know if you expected some other behaviour from the build script

2021-09-04 18:12 UTC, reinvantveer commented
>It might be worth however considering @parasyte's [comment from the discussion about the RNG](https://github.com/ricky26/rust-mega-drive/discussions/3#discussioncomment-1163058) if you're including the RNG in this PR, though that library might fall foul of the same missing intrinsics as you ran into before.

I tried including this, but it trips over #4 unfortunately.

2021-10-10 12:02 UTC, reinvantveer commented
Hi @ricky26 is there anything left to do here, or could we merge?

2021-10-10 20:28 UTC, ricky26 requested changes
Oh my gosh, I missed the last push on this so I though I was still waiting for changes. Only one minor thing then I'll merge it. Sorry again!

2021-10-10 20:28 UTC, ricky26 commented on libs/megadrive-graphics/default_font.py
> +    output_path = 'src/default_ascii.rs'
```suggestion
    output_path = os.path.join(os.environ['OUT_DIR'], 'default_ascii.rs')
```
Cargo build scripts should write to `$OUT_DIR`. The output shouldn't be checked in any more (it'll be regenerated if needed on build).

2021-10-11 08:25 UTC, reinvantveer commented on libs/megadrive-graphics/default_font.py
> +    output_path = 'src/default_ascii.rs'
Ah I see. Fixed in fb88f9416edcdafd273462b96a2f6d3f9db5064f and 50c230c1ed40b1b2009804f2b219cc51d06ea223

2021-10-11 08:25 UTC, ricky26 commented on libs/megadrive-graphics/src/lib.rs
> +pub mod default_ascii;
I think this also needs to be changed to make it build again.

```suggestion
pub mod default_ascii {
    include!(concat!(env!("OUT_DIR"), "/default_ascii.rs")))
}
```

2021-10-11 08:28 UTC, reinvantveer commented on libs/megadrive-graphics/src/lib.rs
> +pub mod default_ascii;
Ah I was just wondering how that should work

2021-10-11 08:32 UTC, reinvantveer commented on libs/megadrive-graphics/src/lib.rs
> +pub mod default_ascii;
Oh, but now it doesn't compile, let me check

2021-10-11 08:34 UTC, ricky26 commented on libs/megadrive-graphics/build.rs
> +    println!("cargo:rerun-if-changed=src/default_ascii.rs");
This file shouldn't exist any more.

2021-10-11 08:34 UTC, ricky26 commented on libs/megadrive-graphics/build.rs
> +    println!("cargo:rerun-if-changed=build.rs");
I don't believe you need to specify `build.rs` here, it should always be re-run if the build script has changed.`

2021-10-11 08:43 UTC, reinvantveer commented on libs/megadrive-graphics/src/lib.rs
> +pub mod default_ascii;
The Docker image now requires Python of course, fixed in d1a4cacc2421c98c9004b7d6e9098ab899b4e256

2021-10-11 08:46 UTC, reinvantveer commented on libs/megadrive-graphics/build.rs
> +    println!("cargo:rerun-if-changed=src/default_ascii.rs");
Correct :). 08d4d7d5deba9712ce6e22398dbd08ce466f18b3

2021-10-11 08:46 UTC, reinvantveer commented on libs/megadrive-graphics/build.rs
> +    println!("cargo:rerun-if-changed=build.rs");
Appears that is true. Checked with the `build.sh` and it compiles just fine without. 08d4d7d5deba9712ce6e22398dbd08ce466f18b3

2021-10-11 08:48 UTC, reinvantveer commented on libs/megadrive-graphics/default_font.py
> +    output_path = 'src/default_ascii.rs'
Just slighty fiddly to get the hang of the `build.rs` system, but it looks like it's getting pretty Rust-idiomatic

2021-10-11 09:53 UTC, ricky26 approved these changes
This looks good to me now. Are you happy for me to merge?

2021-10-11 13:32 UTC, reinvantveer commented
> This looks good to me now. Are you happy for me to merge?

Sure thing, hit it!

2021-10-11 13:46 UTC, merged

2021-10-11 15:36 UTC, reinvantveer commented
:raised_hands: